apiVersion: v1
kind: Service
metadata:
  name: cortex-frontend
  namespace: cortex
  labels:
    app: cortex-frontend
spec:
  selector:
    app: cortex-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

