apiVersion: v1
kind: Service
metadata:
  name: cortex-backend
  namespace: cortex
  labels:
    app: cortex-backend
spec:
  selector:
    app: cortex-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

